update config
emaicorp/altSchool-social-media pull request #9
Opened 2024-08-16 09:06 UTC by dpilot4ever

The db.js file in the config folder has been removed.

2024-08-16 19:09 UTC, emaicorp requested changes
This is how your config file should look like ![Screenshot_2024-08-16-20-08-22-674_com.whatsapp.png](https://github.com/user-attachments/assets/eb7ca52c-5dcb-4250-963d-50df91f9974d)

2024-08-19 07:49 UTC, dpilot4ever commented
Good morning sir, regards to your lovely family.
I thought you said I should not include it. It's the db.js file.
Warm regards.

On Fri, 16 Aug 2024, 20:09 emaicorp, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> This is how your config file should look like Screenshot_2024-08-16-20-08-22-674_com.whatsapp.png
> (view on web)
> <https://github.com/user-attachments/assets/eb7ca52c-5dcb-4250-963d-50df91f9974d>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/emaicorp/altSchool-social-media/pull/9#pullrequestreview-2243389059>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALS2BJRKGX3W73O65F26SETZRZFAJAVCNFSM6AAAAABMTWC7BWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDENBTGM4DSMBVHE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-08-19 08:19 UTC, emaicorp requested changes
Where is the database config there is no file for the database config so look at the link I sent to the group and figure out how to fix yours

2024-08-24 18:43 UTC, emaicorp approved these changes

2024-08-24 18:45 UTC, merged